services:
  backend:
    container_name: web-bounty-flw-backend
    image: web-bounty-flw-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8181:8080"
    volumes:
      - ./data:/app/data
    environment:
      - BFLOW_ADDR=:8080
  frontend:
    container_name: web-bounty-flw-frontend
    image: web-bounty-flw-frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - backend
