services:
  backend:
    container_name: web-bounty-flw-backend
    image: web-bounty-flw-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./organizations:/app/organizations
      - ./wildcards:/app/wildcards
      - ./domains:/app/domains
      - ./apidomains:/app/apidomains
      - ./ips:/app/ips
      - ./out-of-scope:/app/out-of-scope
    environment:
      - BFLOW_ADDR=:8080
  frontend:
    container_name: web-bounty-flw-frontend
    image: web-bounty-flw-frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - backend
